version: "3.8"
services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"

  sensor-generator:
    build:
      context: ./sensor-generator
    container_name: sensor-generator
    depends_on:
      - mqtt-broker

  data-processor:
    build:
      context: ./data-processor
    container_name: data-processor
    depends_on:
      - mqtt-broker